import Head from "next/head";
import Background from "../../components/Background";
import Sidebar from "../../components/Sidebar";
import { motion } from "framer-motion";
import ThemeSwitcher from "../../components/ThemeSwitcher";
import frontendData from "../../data/frontendData";
import fullstackData from "../../data/fullstackData";
import WorkList from "../../components/WorkList";
import { useState } from "react";
import ButtonWorks from "../../components/ButtonWorks";

const Works = () => {
  const [activeTab, setActiveTab] = useState("frontend");
  return (
    <>
      <Head>
        <title>Daffa Wijaya | Works</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.png" />
      </Head>

      <main className="h-screen flex fixed w-[15%] h-full z-50">
        <Sidebar />
      </main>

      <main className="h-screen bg-black dark:bg-white flex fixed w-screen z-10">
        <Background />
      </main>

      <div className="relative h-screen z-20">
        <div className="relative z-20 flex flex-col justify-center h-full ">
          {/* title */}
          <div className="ml-[17%] lg:py-6 pb-3 lg:fixed relative z-20 italic lg:h-full">
            <div className="flex justify-center h-full flex-col">
              <motion.h1
                initial={{ left: -200, opacity: 0 }}
                animate={{ left: 0, opacity: 100 }}
                transition={{
                  delay: 0,
                  duration: 1,
                }}
                className="relative text-a-2 text-5xl lg:text-7xl font-bold pb-2 capitalize"
              >
                my Workss
              </motion.h1>
              <motion.div
                initial={{ left: -200, opacity: 0 }}
                animate={{ left: 0, opacity: 1 }}
                transition={{
                  delay: 0.2,
                  duration: 1,
                }}
                className="relative flex flex-col gap-2 mt-4"
              >
                <ButtonWorks
                  label="Frontend Developer"
                  value="frontend"
                  activeTab={activeTab}
                  setActiveTab={setActiveTab}
                />

                <ButtonWorks
                  label="Fullstack Developer"
                  value="fullstack"
                  activeTab={activeTab}
                  setActiveTab={setActiveTab}
                />

                <ButtonWorks
                  label="UI/UX Designer"
                  value="uiux"
                  activeTab={activeTab}
                  setActiveTab={setActiveTab}
                />
              </motion.div>
            </div>
          </div>
          {/* content */}
          {activeTab === "frontend" && <WorkList worksData={frontendData} />}
          {activeTab === "fullstack" && <WorkList worksData={fullstackData} />}

          {activeTab === "uiux" && (
            <div className="ml-[17%] text-black dark:text-white">
              UI/UX projects coming soon...
            </div>
          )}
        </div>
      </div>

      <ThemeSwitcher />
    </>
  );
};

export default Works;
