import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Contact from '../components/Contact'
import Image from 'next/image'
import { motion } from 'framer-motion'
import ThemeSwitcher from '../components/ThemeSwitcher'

export default function Home() {
  return (
    <>
      <Head>
        <title>Daffa Wijaya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.png" />
      </Head>

      <main className='h-screen flex fixed w-[15%] h-full z-50'>
        <Sidebar />
      </main>

      <main className='w-[85%] h-screen bg-black flex ml-[15%]'>
        <div className="absolute inset-0 w-screen z-0 h-full dark:md:bg-[url('/bgl.png')] dark:bg-[url('/bgv.png')] md:bg-[url('/bgli.png')] bg-[url('/bgvi.png')] bg-cover bg-center">
          <div className='absolute dark:backdrop-brightness-[0.3] h-full w-full' />
        </div>
        <div className='absolute w-[10%] h-full z-10 '>
          
        </div>
        <div className="relative z-20 w-full h-full relative flex flex-col items-center justify-center">
          <motion.div
            whileHover={{
              scale: 1.02,
              transition: { duration: 0.3 },
            }}
            initial={{ bottom: -100, opacity: 0 }}
            animate={{ bottom: 0, opacity: 100 }}
            transition={{
              delay: 0,
              duration: 1
            }}
            className="bg-[url('/dafaaalogo2i2.png')] dark:bg-[url('/dafaaalogo2.png')] relative lg:h-[290px] lg:w-[400px] sm:h-[220px] sm:w-[300px] bg-cover h-[180px] w-[240px] mr-[15%]">
          </motion.div>
        </div>
      </main>
      <ThemeSwitcher />
    </>
  )
}

